name = "tvbox-source-aggregator"
main = "src/cf-entry.ts"
compatibility_date = "2026-05-02"
compatibility_flags = [ "nodejs_compat" ]

# 告诉 Cloudflare 我需要一个叫 KV 的绑定
# ID 留空，发布后去网页后台手动绑定
[[kv_namespaces]]
binding = "KV"
id = "" 

[triggers]
crons = ["0 * * * *"]

[vars]
# 这里的域名可以不填，或者填你以后想用的
WORKER_BASE_URL = ""
