name = "tvbox-source-aggregator"
main = "src/cf-entry.ts"
compatibility_date = "2026-05-02"
compatibility_flags = [ "nodejs_compat" ]

# 不要写 [[kv_namespaces]] 这几行代码了！
# 我们直接在网页后台手动绑定，这样你的 ID 就不会出现在 GitHub 上。

[triggers]
crons = ["0 * * * *"]

[vars]
# 这里也可以留空，稍后在网页后台手动填入，保护隐私
WORKER_BASE_URL = ""
